line_length: 200
large_tuple: 5
function_parameter_count: 6
identifier_name:
  excluded: # excluded via string array
    - i

disabled_rules:
  - force_cast
  - force_try
  - trailing_whitespace

use_nested_configs: true
